spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - ${FRONTEND_URL:http://localhost:5173}
                  - http://127.0.0.1:5173
                allowed-methods:
                  - GET
                  - POST
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - X-Entry-Token
                allow-credentials: true
          routes:
            - id: queue-service
              uri: ${QUEUE_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/schedules/*/queues/**
            - id: ticket-service
              uri: ${TICKET_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/concerts/**,/api/admin/**,/api/schedules/**,/api/reservations/**
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/payments/**

server:
  port: 8080

jwt:
  issuer: seat-rush-ticket-service
  public-key-location: classpath:cert/public-key.pem

